# Generated by Django 3.1.7 on 2021-03-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='moodres',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
