# Generated by Django 3.1.7 on 2021-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0007_auto_20210312_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diary',
            name='moodres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
